version: "3.3"
services:
  # MariaDB
  mysql:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyDBRoot123 
      MYSQL_DATABASE: cloud_computing
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    networks:
      - mynet

  # PHP-FPM
  myphp:
      build:   # build from Dockerfile , not a official image
        context: ./src/php   # dir is ./src/php/dockerfile
      ports:
        - "9000"
      volumes:
        - ./src/:/var/www/html
          # - ./src/myproj:/var/www/html

      depends_on:
        - mysql
      restart: always
      networks:
        - mynet
  
  # Nginx http://external_ip:8080/the_phpfile.php
  mynginx:
    image: nginx:latest
    ports:
      - "8080:80"   # host:container format
    volumes:
      - ./src/nginx.ini:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
        #- ./src/myproj:/var/www/html

    depends_on:
      - myphp
    restart: always
    networks:
      - mynet
  # Codeigniter
    #  codeigniter:
    #image: shinsenter/codeigniter4:latest
    # volumes:
    #depends_on:
    # - myphp
    #restart: always
    #networks:
    # - mynet


  # phpMyAdmin http://external_ip:8082
  phpMyAdmin:
    image: phpmyadmin:latest
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
    restart: always
    networks:
        - mynet
    depends_on:
      - mysql
networks:
    mynet:
      driver: bridge

# environment value of phpmyadmin:PMA_HOST reference: https://hub.docker.com/_/phpmyadmin 
# run: docker-compose up -d

